version: "3"

services:
  node-app:
    container_name: beckend
    image: nestapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
      image: postgres
      container_name: task
      environment:
        - POSTGRES_USER=anvar
        - POSTGRES_PASSWORD=312434151
        - POSTGRES_DB=task
      ports:
        - '6300:5432'
